### ISSUE TITLE
installed cli.then ‘npm start’ the first project.Error: caches is not defined.

### ISSUE THREAD

**Issue by GordenMo** [signageos/cli#28]
![image](https://user-images.githubusercontent.com/52969451/217449571-f979ba6e-30bd-4544-a0b0-23a7c8a809fd.png)

shell：
![image](https://user-images.githubusercontent.com/52969451/217449671-39667ae9-00f3-4abc-84d5-9bf802eea3e0.png)

**Comment by misak113** [comment]
Hi, thank you for the report. Can you give me more information about the browser you are using?
The emulator (latest version) is using some modern APIs like IndexedDB and Cache API that is available in the latest Chromium, Firefox, Edge, and other. But not all browsers support that.

**Comment by GordenMo** [comment]
@misak113 
the browser version is  Microsoft Edge(109.0.1518.70).
it is same when browing in the Chrome(109.0.5414.120).

**Comment by misak113** [comment]
Hi, ok. Those browsers should be supported. Can you please try to use the localhost in URL instead of any possible IP address?
The Cache API features are available only in a secured context or on localhost (as a development exception).
We will try to fix this behavior in the CLI so you are not navigated to IP address in the console output.
