### ISSUE TITLE
Error while login

### ISSUE THREAD

**Issue by rsegovia** [signageos/cli#31]
steps to reproduce:
sos login
Type your username or e-mail used for box.signageos.io: 
Type your password used for box.signageos.io
"Unknown error: Server error - The "salt" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, or DataView. Received undefined"

This error only happen if the e-mail is registered, if we type a wrong email, we receive the message "Incorrect username or password"

**Comment by misak113** [comment]
The problem was initiated by migrating the authentication process to Auth0 provider.
The fix has been released in version [1.4.1](https://github.com/signageos/cli/blob/master/CHANGELOG.md#141---2023-10-02).
```sh
npm install @signageos/cli@latest -g
sos login
```

You can still use version 1.4.0 but with the additional hidden argument `--auth0-enabled`.
```sh
sos login --auth0-enabled
```

You can use any older 1.x (`<1.4.0`) version without any additional argument as the authentication method is selected automatically.
```sh
sos login
```
